  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Exécuter Prettier
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --check .
