name: Analyse de code avec Prettier

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Analyse du code avec Prettier
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --check .
